# Generated by Django 5.1.5 on 2025-02-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
